mod builder;
mod colors;
mod sequences;
mod shell;
mod traits;
pub use builder::TermPromptBuilder;
pub use builder::TermType;
pub use colors::NamedColor;
pub use sequences::TermSequence;
pub use traits::ColoredTermPrompt;
